// Generated by CoffeeScript 2.2.4
var gulp, uglify;

gulp = require('gulp');

({
  default: uglify
} = require('gulp-uglify-es'));

gulp.task('min', function() {
  return gulp.src(['lib/**/*.js']).pipe(uglify()).pipe(gulp.dest('out'));
});
